stages:
  - build
  - publish

.common: &common
  tags:
    - docker
    - ubuntu
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

build:
  <<: *common
  stage: build
  script:
    - docker build -f ci/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID .
    - docker save $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID | gzip > image.tar.gz
  artifacts:
    expire_in: 24 hours
    paths:
      - image.tar.gz

publish:
  <<: *common
  stage: publish
  dependencies:
    - build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - zcat image.tar.gz | docker load
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  when: manual
